#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHECKPOINT_DIR="$ROOT_DIR/checkpoints"
mkdir -p "$CHECKPOINT_DIR/ShapeLLM_7B_gapartnet_v1.0" \
         "$CHECKPOINT_DIR/Uni3D/uni3d-b" \
         "$CHECKPOINT_DIR/recon" \
         "$CHECKPOINT_DIR/mm_projector"

fetch() {
  local url="$1"
  local out="$2"
  echo "Downloading: $out"
  mkdir -p "$(dirname "$out")"
  curl -fL --retry 5 --retry-all-errors --continue-at - "$url" -o "$out"
}

# 1) ShapeLLM 7B GapartNet checkpoint
BASE_SHAPELLM="https://huggingface.co/qizekun/ShapeLLM_7B_gapartnet_v1.0/resolve/main"
fetch "$BASE_SHAPELLM/config.json?download=true" "$CHECKPOINT_DIR/ShapeLLM_7B_gapartnet_v1.0/config.json"
fetch "$BASE_SHAPELLM/generation_config.json?download=true" "$CHECKPOINT_DIR/ShapeLLM_7B_gapartnet_v1.0/generation_config.json"
fetch "$BASE_SHAPELLM/pytorch_model-00001-of-00002.bin?download=true" "$CHECKPOINT_DIR/ShapeLLM_7B_gapartnet_v1.0/pytorch_model-00001-of-00002.bin"
fetch "$BASE_SHAPELLM/pytorch_model-00002-of-00002.bin?download=true" "$CHECKPOINT_DIR/ShapeLLM_7B_gapartnet_v1.0/pytorch_model-00002-of-00002.bin"
fetch "$BASE_SHAPELLM/pytorch_model.bin.index.json?download=true" "$CHECKPOINT_DIR/ShapeLLM_7B_gapartnet_v1.0/pytorch_model.bin.index.json"
fetch "$BASE_SHAPELLM/special_tokens_map.json?download=true" "$CHECKPOINT_DIR/ShapeLLM_7B_gapartnet_v1.0/special_tokens_map.json"
fetch "$BASE_SHAPELLM/tokenizer.model?download=true" "$CHECKPOINT_DIR/ShapeLLM_7B_gapartnet_v1.0/tokenizer.model"
fetch "$BASE_SHAPELLM/tokenizer_config.json?download=true" "$CHECKPOINT_DIR/ShapeLLM_7B_gapartnet_v1.0/tokenizer_config.json"

# Optional metadata artifacts kept for completeness
fetch "$BASE_SHAPELLM/README.md?download=true" "$CHECKPOINT_DIR/ShapeLLM_7B_gapartnet_v1.0/README.md"
fetch "$BASE_SHAPELLM/trainer_state.json?download=true" "$CHECKPOINT_DIR/ShapeLLM_7B_gapartnet_v1.0/trainer_state.json"
fetch "$BASE_SHAPELLM/training_args.bin?download=true" "$CHECKPOINT_DIR/ShapeLLM_7B_gapartnet_v1.0/training_args.bin"

# 2) ReCon++ large checkpoint
fetch "https://huggingface.co/qizekun/ReConV2/resolve/main/zeroshot/large/best_lvis.pth?download=true" \
      "$CHECKPOINT_DIR/recon/large.pth"

# 3) Uni3D-B checkpoint
fetch "https://huggingface.co/BAAI/Uni3D/resolve/main/modelzoo/uni3d-b/model.pt?download=true" \
      "$CHECKPOINT_DIR/Uni3D/uni3d-b/model.pt"

# 4) URDF-Anything evaluation checkpoint
fetch "https://huggingface.co/only34U/urdf-anything/resolve/main/last.ckpt?download=true" \
      "$CHECKPOINT_DIR/last.ckpt"

# mm_projector is generated by training; leave the directory ready.
if [[ ! -f "$CHECKPOINT_DIR/mm_projector/mm_projector.bin" ]]; then
  echo "Note: $CHECKPOINT_DIR/mm_projector/mm_projector.bin is not publicly provided; it is usually created during training."
fi

echo "Done."
